package it.antonio.sp.util;

public class Constants {
	// Role constant variables
	public static final String ROLE_ADMIN = "ROLE_ADMIN";
	public static final String ROLE_ADMIN_SPECIALTIES_ALL = "ROLE_ADMIN_SPECIALTIES_ALL";
	public static final String ROLE_ADMIN_QUALIFICATIONS_ALL = "ROLE_ADMIN_QUALIFICATIONS_ALL";
	public static final String ROLE_ADMIN_USER_MANAGEMENT_ALL = "ROLE_ADMIN_USER_MANAGEMENT_ALL";

	public static final String ROLE_USER_DASHBOARD_ALL = "ROLE_USER_DASHBOARD_ALL";
	public static final String ROLE_USER_REPORTS_BY_TURNO_ALL = "ROLE_USER_REPORTS_BY_TURNO_ALL";
	public static final String ROLE_USER_REPORTS_BY_SPECIALTY_ALL = "ROLE_USER_REPORTS_BY_SPECIALTY_ALL";
	public static final String ROLE_USER_REPORTS_BY_EXPIRED_SPECIALTY_ALL = "ROLE_USER_REPORTS_BY_EXPIRED_SPECIALTY_ALL";

	public static final String ROLE_USER_ANAGRAPHICVVF_VIEW = "ROLE_USER_ANAGRAPHICVVF_VIEW";
	public static final String ROLE_USER_ANAGRAPHICVVF_INSERT = "ROLE_USER_ANAGRAPHICVVF_INSERT";
	public static final String ROLE_USER_ANAGRAPHICVVF_EDIT = "ROLE_USER_ANAGRAPHICVVF_EDIT";
	public static final String ROLE_USER_ANAGRAPHICVVF_DELETE = "ROLE_USER_ANAGRAPHICVVF_DELETE";

	public static final String ROLE_USER_SPECIALTY_VIEW = "ROLE_USER_SPECIALTY_VIEW";
	public static final String ROLE_USER_SPECIALTY_INSERT = "ROLE_USER_SPECIALTY_INSERT";
	public static final String ROLE_USER_SPECIALTY_EDIT = "ROLE_USER_SPECIALTY_EDIT";
	public static final String ROLE_USER_SPECIALTY_DELETE = "ROLE_USER_SPECIALTY_DELETE";
}
